package BluetoothManager_test

import (
	"fmt"
	"testing"

	"github.com/stretchr/testify/assert"
)

func TestConnectCommandGeneration(t *testing.T) {
    deviceAddress := "00:11:22:33:AA:BB"
    expectedCommands := []string{
        "connect 00:11:22:33:AA:BB\n",
        "exit\n",
    }
    commands := []string{
        fmt.Sprintf("connect %s\n", deviceAddress),
        "exit\n",
    }

    assert.Equal(t, expectedCommands, commands, "The commands generated by Connect should match the expected commands.")
}

func TestDisconnectCommandGeneration(t *testing.T) {
    deviceAddress := "00:11:22:33:AA:BB"
    expectedCommands := []string{
        "disconnect 00:11:22:33:AA:BB\n",
        "exit\n",
    }
    commands := []string{
        fmt.Sprintf("disconnect %s\n", deviceAddress),
        "exit\n",
    }

    assert.Equal(t, expectedCommands, commands, "The commands generated by Disconnect should match the expected commands.")
}